spring:
  application:
    name: dubbo-demo-consumer
  main:
    banner-mode: 'off'
  jackson:
    default-property-inclusion: non_null
  mvc:
    view:
      prefix: /
      suffix: .jsp
  profiles:
    active: '@activatedProperties@'

# Logging
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  file: ${user.home}/logs/dubbo-demo-consumer.log
  level:
    root: info
    org.springframework.web: debug
    com.noisyle: debug

# Tomcat Access Logging
server:
  tomcat:
    accesslog:
      enabled: true
      directory: ${user.home}/logs/
      prefix: dubbo-demo-provider_access
      pattern: '%t %a "%r" %s (%D ms)\n "%{User-Agent}i"'
