spring:
  application:
    name: dubbo-demo-consumer
  main:
    banner-mode: 'off'
  profiles:
    active: '@activatedProperties@'

# Logging
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  file: ${user.home}/logs/${spring.application.name}-${server.port}.log
  level:
    root: info
    org.springframework.web: debug
    com.noisyle: debug
