server:
  port: 8010

dubbo:
  scan:
    basePackages: com.noisyle.dubbo.service
  application:
    qosEnable: false
  registry:
    id: dev-registry
    protocol: multicast
    address: 224.5.6.7:12345