spring:
  application:
    name: dubbo-demo-provider
  main:
    banner-mode: 'off'
  profiles:
    active: '@activatedProperties@'

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    root: info
    com.noisyle: debug
