server:
  port: 8010

dubbo:
  scan:
    basePackages: com.noisyle.dubbo.service
  application:
    qosEnable: false
  registry:
    id: prod-registry
    protocol: zookeeper
    address: 192.168.96.91:2181